"""Add clients table

Revision ID: 39e8ef751e4a
Revises: 7ecf754749f7
Create Date: 2024-03-10 21:47:03.460561

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '39e8ef751e4a'
down_revision = '7ecf754749f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_on', sa.DateTime(), nullable=False),
                    sa.Column('updated_on', sa.DateTime(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(), nullable=False),
                    sa.Column('identifier', sa.String(), nullable=False),
                    sa.Column('secret_hash', sa.LargeBinary(), nullable=False),
                    sa.Column('secret_salt', sa.LargeBinary(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_identifier'), 'clients', ['identifier'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_identifier'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
