"""Add measurements table

Revision ID: a24aa7b2d612
Revises: b0cbd40923b6
Create Date: 2024-03-10 21:48:18.359048

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a24aa7b2d612'
down_revision = 'b0cbd40923b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurements',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_on', sa.DateTime(), nullable=False),
                    sa.Column('updated_on', sa.DateTime(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(), nullable=False),
                    sa.Column('timestamp', sa.BigInteger(), nullable=False),
                    sa.Column('voltage', sa.DECIMAL(precision=9, scale=7), nullable=False),
                    sa.Column('current', sa.DECIMAL(precision=9, scale=7), nullable=False),
                    sa.Column('experiment_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_measurements_id'), 'measurements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_measurements_id'), table_name='measurements')
    op.drop_table('measurements')
    # ### end Alembic commands ###
